// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zandrbmbygxxnugteuci.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphbmRyYm1ieWd4eG51Z3RldWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDE3MjUsImV4cCI6MjA3MzM3NzcyNX0.xo15ZY4K6Eb6G7YxYNxKW3A2xJDSwWjbsNLxPyEpkoY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});